[package]
name = "chess"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
vampirc-uci = "0.9.0"
futures = "0.3.30"
async-std = "1.12.0"
